### ISSUE TITLE
Dimension: Dynamic Expression works in "Label Expression" but not in "Label Description"

### ISSUE THREAD

**Issue by rvaheldendaten** [RobWunderlich/qcb-qlik-sse#10]
Hi!

I have a strange behavior!

I use a dynamic expression for a multilanguage app.

=$(vT('dimlabel./BI0/PCUSTOMER.CITY'))

Dimensions are created via QCB.

When I use this for the dimension label, the Master Item shows the label correctly. (blue in screenshot)
When I use the same expression for the dimensions description, Qlik does not interpret the function, but still shows the expression. (red in screenshot)

![qcb_Description](https://user-images.githubusercontent.com/11175181/100898421-0a3c7980-34c1-11eb-8889-7bdc3c41e5fe.png)

When I now manually edit the Master Item, and replace the EQUAL-Sign it suddenly works.

![qcb_Description2](https://user-images.githubusercontent.com/11175181/100898966-9cdd1880-34c1-11eb-875b-6faf64520a1e.png)

I was able to reproduce this on two systems. Any idea why this happens?

Thx,
Roland

**Comment by RobWunderlich** [comment]
Which qcb function are you using to create the DImension?

**Comment by rvaheldendaten** [comment]
I use 

Creator:
LOAD 
  *,
QCB.CreateDimension(DimName, FieldName, DimDescription, DimTags, DimLabel) as DimensionState
resident QCB_Dimension;
  
I can provide you the input table if helpful. Problem seems to be "DimDescription"

**Comment by RobWunderlich** [comment]
Commit 26efcb36f020a168122b0808ee774aaa33403c1e should fix this issue.

**Comment by rvaheldendaten** [comment]
thx, works fine! 

Could it be that QCB.CreateMeasure has a similar issue? i have to doublecheck it on another system, but again if I have a dynamic description for the masteritem it doest not work!

![image](https://user-images.githubusercontent.com/11175181/102237351-e0d61180-3ef4-11eb-9d2f-59f91cd0b480.png)

**Comment by RobWunderlich** [comment]
Yes, I imagine it would be the same problem. I'll reopen this issue and update CreateMeasure as well.

**Comment by rvaheldendaten** [comment]
See my pull request. Looks good from my tests: Dynamic expression =chr(65)&today()  is now shown correctly.

![createMeasure](https://user-images.githubusercontent.com/11175181/104619636-6680e480-568e-11eb-92e1-229cc1dc80c0.png)
