### ISSUE TITLE
 error when using NPM Install

### ISSUE THREAD

**Issue by WedersonCD** [RobWunderlich/qcb-qlik-sse#2]
Good Morning!

When i run 'npm instal'(In PowerShell as administrator) in qcb root folder, i'm getting the following error:
`  z.vcxproj -> D:\SSE\node_modules\grpc\build\Release\\libz.lib
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1`

(Full error attached)

npm version: 6.13.4
node version: 13.6.0
python version: 3.8.2

SO: Windows 10.

[error.txt](https://github.com/RobWunderlich/qcb-qlik-sse/files/4431297/error.txt)

**Comment by RobWunderlich** [comment]
There are numerous reports of failures trying to install grpc using Node 12+. For example https://github.com/grpc/grpc-node/issues/1086. I use Node 10 as a workaround.

**Comment by WedersonCD** [comment]
> There are numerous reports of failures trying to install grpc using Node 12+. For example [grpc/grpc-node#1086](https://github.com/grpc/grpc-node/issues/1086). I use Node 10 as a workaround.

Thanks for reply! solved my problem.

I try using node 12.16 version and works fine c:
