### ISSUE TITLE
Call a function in script without a Load statement

### ISSUE THREAD

**Issue by WedersonCD** [RobWunderlich/qcb-qlik-sse#4]
Good Morning!

I'm working on a generic function to create functions based on QVS files, and is working fine. At the base, the functions return a string that Qlik  needs to eval, like a SET variable.

But i dont find a nice way to call this functions.. because i only can send data to SEE  in the script using a Load Statement...

Have a better way to invoke this functions?

Calling Functions in the front.
![QCB_1](https://user-images.githubusercontent.com/28493584/80123580-776c5180-8565-11ea-9a07-3858b5c66f63.png)

Calling Functions in the script
![QCB_2](https://user-images.githubusercontent.com/28493584/80123583-789d7e80-8565-11ea-83ab-d36a1057c3e8.png)
![QCB_3](https://user-images.githubusercontent.com/28493584/80123584-789d7e80-8565-11ea-886c-904af4e05b1f.png)

obs:
I don't know if this is the right place to post a question(Git noob here), let me know if was a best way to post question's like that.

**Comment by RobWunderlich** [comment]
You can invoke functions in script using a LET statement.

LET vStoreQVd = QCB.StoreQvd(...);

**Comment by WedersonCD** [comment]
works c:
